[package]
name = "air001-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
air001-rs-macros = { path = "macros" }
volatile = "0.5.1"

[[example]]
name = "blinky"
